### ISSUE TITLE
Is it ethical to close the tab in the web browser?

### ISSUE THREAD

**Issue by floppydiskette** [heyseth/worm-sim#2]
I really like the worm simulator, but I'm worried about the potential ethical impact of closing the browser tab. Does it kill the worm or will the worm be okay?

Somewhat related, a feature to save the state of your worm might be nice so that you can transfer the worm between computers, or restore your worm to an earlier point if you're disappointed with it

**Comment by lassethorlepik** [comment]
Given the worm is eternally kept in a constant state of hunger, I feel a blow of mercy by closing the tab could even be considered ethically preferred.

Given the worm is released under MIT, anyone is able to spin up thousands of worm brain instances and set up a script to torture / kill them again and again. For example removing food in front of the worm as it is about to consume it, making it a Sisyphean task. This would be the ethically problematic part.

**Comment by elapt1c** [comment]
lmaooo this is the funniest github comment ever. somebody scared about the feelings of a virtual worm (they dont have feelings. they have like 300 neurons ur gonna be ok 💀)

**Comment by heyseth** [comment]
Not sure if this is serious, but as the poster above has stated, the worm only has 302 neurons. If consciousness derives from the integration of information, than it is extremely unlikely that the worm has an inner life.

Still, this raises the question of at what point simulations of this sort become unethical, which I don't have an answer to.

**Comment by dimalmfao** [comment]
bro that’s hell of an issue, it’s a simulation, not a real living worm

**Comment by suspicious-pineapple** [comment]
I suggest storing the state of the worm in localStorage as a workaround for this issue.
