### ISSUE TITLE
Is my simulation broken or are c. elegans this stupid

### ISSUE THREAD

**Issue by DrakeFruit** [heyseth/worm-sim#5]
I'm placing food directly in front of the worm, and it's just avoiding it entirely? it feels like their movements are just completely random

**Comment by heyseth** [comment]
This behavior in the simulation is normal. In reality, real c elegans worms are a bit smarter than the simulated one. This is because we still don't actually know the 'weight' of each neuron, only the connections it has, so the simulation is far from perfect.

**Comment by multitrack-collector** [comment]
By "we", do you mean the actual scientific community? Also, why can't we train the c elegans using back propagation, assuming we have some sort of data to validate an input with an output?
